### ISSUE TITLE
Corregir error de arranque de stork-commons.log

### ISSUE THREAD

**Issue by jrc29v** [carm-es/inside#104]
Durante el arranque del servidor Inside se produce un error relacionado con la ubicación de la librería "stork-commons.log"

java.io.FileNotFoundException: /opt/storklogs/stork-commons.log (No existe el fichero o el directorio)

Revisar la ubicación de dicha librería y corregirla

**Comment by jrc29v** [comment]
Dejo copia de la traza de arranque del fichero catalina.out

20-Jul-2022 03:00:31.369 INFORMACIÃ“N [main] org.apache.catalina.core.StandardServer.await Se ha recibido un comando de apagado a travÃ©s del puerto de apagado. Parando la instancia del Servidor.
20-Jul-2022 03:00:31.370 INFORMACIÃ“N [main] org.apache.coyote.AbstractProtocol.pause Pausing ProtocolHandler ["http-nio-9040"]
2022-07-20 03:00:31,729  WARN HttpSessionSecurityContextRepository:343 - Failed to create a session, as response has been committed. Unable to store SecurityContext.
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
20-Jul-2022 03:00:43.511 INFORMACIÃ“N [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.5.20
20-Jul-2022 03:00:43.513 INFORMACIÃ“N [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Aug 2 2017 21:35:49 UTC
20-Jul-2022 03:00:43.513 INFORMACIÃ“N [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.5.20.0
20-Jul-2022 03:00:43.513 INFORMACIÃ“N [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
20-Jul-2022 03:00:43.513 INFORMACIÃ“N [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.9.0-8-amd64
20-Jul-2022 03:00:43.513 INFORMACIÃ“N [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
20-Jul-2022 03:00:43.513 INFORMACIÃ“N [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /opt/jdk1.8.0_202/jre
20-Jul-2022 03:00:43.513 INFORMACIÃ“N [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_202-b26
20-Jul-2022 03:00:43.513 INFORMACIÃ“N [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
20-Jul-2022 03:00:43.513 INFORMACIÃ“N [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /opt/tomcat-inside
20-Jul-2022 03:00:43.513 INFORMACIÃ“N [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /opt/tomcat-inside
20-Jul-2022 03:00:43.514 INFORMACIÃ“N [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/opt/tomcat-inside/conf/logging.properties
20-Jul-2022 03:00:43.514 INFORMACIÃ“N [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
20-Jul-2022 03:00:43.514 INFORMACIÃ“N [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
20-Jul-2022 03:00:43.514 INFORMACIÃ“N [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
20-Jul-2022 03:00:43.514 INFORMACIÃ“N [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -DjvmRoute=jvminsidepro1
20-Jul-2022 03:00:43.514 INFORMACIÃ“N [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms256m
20-Jul-2022 03:00:43.514 INFORMACIÃ“N [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx5g
20-Jul-2022 03:00:43.514 INFORMACIÃ“N [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:MaxPermSize=256m
20-Jul-2022 03:00:43.514 INFORMACIÃ“N [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.awt.headless=true
20-Jul-2022 03:00:43.514 INFORMACIÃ“N [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+UseG1GC
20-Jul-2022 03:00:43.517 INFORMACIÃ“N [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dconfig.path=/opt/tomcat-inside/conf/inside
20-Jul-2022 03:00:43.518 INFORMACIÃ“N [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2
20-Jul-2022 03:00:43.518 INFORMACIÃ“N [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -DtmpShared.path=/opt/tomcat-inside/datos/
20-Jul-2022 03:00:43.518 INFORMACIÃ“N [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dinside.hostDomainPort=inside.carm.es
20-Jul-2022 03:00:43.518 INFORMACIÃ“N [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djavax.net.ssl.trustStore=/opt/tomcat-inside/conf/inside/trustStore.jks
20-Jul-2022 03:00:43.518 INFORMACIÃ“N [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djavax.net.ssl.trustStorePassword=changeit
20-Jul-2022 03:00:43.518 INFORMACIÃ“N [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/opt/tomcat-inside
20-Jul-2022 03:00:43.518 INFORMACIÃ“N [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/opt/tomcat-inside
20-Jul-2022 03:00:43.518 INFORMACIÃ“N [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/opt/tomcat-inside/temp
20-Jul-2022 03:00:43.518 INFORMACIÃ“N [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent La biblioteca nativa de Apache Tomcat basada en ARP que permite un rendimiento Ã³ptimo en entornos de desarrollo no ha sido hallada en java.library.path: [/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib]
20-Jul-2022 03:00:43.624 INFORMACIÃ“N [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-9040"]
20-Jul-2022 03:00:43.636 INFORMACIÃ“N [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
20-Jul-2022 03:00:43.639 INFORMACIÃ“N [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8040"]
20-Jul-2022 03:00:43.640 INFORMACIÃ“N [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
20-Jul-2022 03:00:43.640 INFORMACIÃ“N [main] org.apache.catalina.startup.Catalina.load Initialization processed in 400 ms
20-Jul-2022 03:00:43.660 INFORMACIÃ“N [main] org.apache.catalina.core.StandardService.startInternal Arrancando servicio [Catalina]
20-Jul-2022 03:00:43.660 INFORMACIÃ“N [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.20
20-Jul-2022 03:00:43.681 INFORMACIÃ“N [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Despliegue del archivo [/opt/tomcat-inside/webapps/inside.war] de la aplicaciÃ³n web
20-Jul-2022 03:00:48.122 INFORMACIÃ“N [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars Al menos un JAR, que se ha explorado buscando TLDs, aÃºn no contenÃ­a TLDs. Activar historial de depuraciÃ³n para este historiador para una completa lista de los JARs que fueron explorados y de los que nos se hallÃ³ TLDs. Saltarse JARs no necesarios durante la exploraciÃ³n puede dar lugar a una mejora de tiempo significativa en el arranque y compilaciÃ³n de JSP .
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /opt/storklogs/stork-commons.log (No existe el fichero o el directorio)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
	at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
	at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
	at org.apache.log4j.DailyRollingFileAppender.activateOptions(DailyRollingFileAppender.java:223)
	at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
	at org.apache.log4j.xml.DOMConfigurator.parseAppender(DOMConfigurator.java:295)
	at org.apache.log4j.xml.DOMConfigurator.findAppenderByName(DOMConfigurator.java:176)
	at org.apache.log4j.xml.DOMConfigurator.findAppenderByReference(DOMConfigurator.java:191)
	at org.apache.log4j.xml.DOMConfigurator.parseChildrenOfLoggerElement(DOMConfigurator.java:523)
	at org.apache.log4j.xml.DOMConfigurator.parseRoot(DOMConfigurator.java:492)
	at org.apache.log4j.xml.DOMConfigurator.parse(DOMConfigurator.java:1006)
	at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:872)
	at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:778)
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
	at org.slf4j.impl.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:64)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:270)
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:156)
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:272)
	at org.springframework.util.PropertyPlaceholderHelper.<clinit>(PropertyPlaceholderHelper.java:40)
	at org.springframework.util.SystemPropertyUtils.<clinit>(SystemPropertyUtils.java:49)
	at org.springframework.util.Log4jConfigurer.initLogging(Log4jConfigurer.java:66)
	at org.springframework.web.util.Log4jWebConfigurer.initLogging(Log4jWebConfigurer.java:151)
	at org.springframework.web.util.Log4jConfigListener.contextInitialized(Log4jConfigListener.java:45)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:988)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1860)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
log4j:ERROR Either File or DatePattern options are not set for appender [MainLogger].
2022-07-20 03:00:52,817  WARN InsideCsvStorageBigDataServiceImpl:91 - Inicializar ruta temp big data transfer a variable csvstorage.bigData.pathTemp
2022-07-20 03:00:52,819  WARN InsideCsvStorageBigDataServiceImpl:96 - /opt/tomcat-inside/datos//shared/
2022-07-20 03:00:53,053 ERROR InsideEniValidationServiceImpl:53 - No se han podido cargar los schemas del directorio: /opt/tomcat-inside/conf/inside/schemas
20-Jul-2022 03:00:59.815 INFORMACIÃ“N [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/opt/tomcat-inside/webapps/inside.war] has finished in [16.133] ms
20-Jul-2022 03:00:59.816 INFORMACIÃ“N [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Despliegue del directorio [/opt/tomcat-inside/webapps/manager] de la aplicaciÃ³n web
20-Jul-2022 03:00:59.975 INFORMACIÃ“N [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars Al menos un JAR, que se ha explorado buscando TLDs, aÃºn no contenÃ­a TLDs. Activar historial de depuraciÃ³n para este historiador para una completa lista de los JARs que fueron explorados y de los que nos se hallÃ³ TLDs. Saltarse JARs no necesarios durante la exploraciÃ³n puede dar lugar a una mejora de tiempo significativa en el arranque y compilaciÃ³n de JSP .
20-Jul-2022 03:00:59.979 INFORMACIÃ“N [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/opt/tomcat-inside/webapps/manager] has finished in [163] ms
20-Jul-2022 03:00:59.982 INFORMACIÃ“N [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-9040"]
20-Jul-2022 03:01:00.012 INFORMACIÃ“N [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8040"]
20-Jul-2022 03:01:00.041 INFORMACIÃ“N [main] org.apache.catalina.startup.Catalina.start Server startup in 16401 ms
2022-07-20 03:01:00,671  WARN UserTokenAuthenticationInterceptor:93 - recibida peticiÃ³n ws por usuario: apli
2022-07-20 03:01:00,700  WARN UserTokenAuthenticationInterceptor:93 - recibida peticiÃ³n ws por usuario: apli
2022-07-20 03:01:00,697  WARN UserTokenAuthenticationInterceptor:93 - recibida peticiÃ³n ws por usuario: apli
